
# export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
# export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
# export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
# export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
# export HOMEBREW_PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

## avoid download json file and revert to old git-based homebrew behaviro
# export HOMEBREW_NO_INSTALL_FROM_API=1

export proxy_ip=127.0.0.1
#test
export vps_ip=3.113.25.205
no_proxy="127.0.0.1,localhost,.localdomain.com"
no_proxy=$no_proxy,${proxy_ip}
export no_proxy

export http_proxy="http://${proxy_ip}:20171"
export https_proxy="http://${proxy_ip}:20171"
export sock_proxy="socks5://${proxy_ip}:20170"

. "$HOME/.cargo/env"

