[[database]]
Name = 'menu-sqlite'
Provider = 'sqlite3'
URL = 'file:/Users/dl/Code/backend/db.sqlite3?loc=auto'

[[database]]
Name = 'Rss-reader'
Provider = 'postgres'
DBName = 'hackernews'
URL = 'postgresql://hacker:hacker123@postgres.hackernews.svc.cluster.local:5432/hackernews?sslmode=disable'
Commands = [
    { Command = 'kubectl -n hackernews port-forward service/postgres 5432:5432 ', WaitForPort = '5432' },
]
[[database]]
Name = 'pre-commit'
Provider = 'sqlite3'
URL = 'file:/Users/dl/.cache/pre-commit/db.db?loc=auto'
